import '../op/operation.dart';

/// A batch of operations that changed local state, and where they came
/// from. [SyncedDoc], [SyncedCounter] and [SyncedSet] listen to
/// [LocalStore.changes] to know when to re-render.
class OpBatch {
  /// Ids of documents touched by this batch.
  final Set<String> docIds;

  /// True if these operations arrived from a remote sync adapter rather
  /// than being generated by a local [SyncedDoc.update] call.
  final bool fromRemote;

  const OpBatch({required this.docIds, required this.fromRemote});
}

/// Persists sync_kit's op log: every write, local or remote, captured as an
/// immutable [Operation] rather than a final value.
///
/// A [LocalStore] is intentionally CRDT-agnostic — it only knows how to
/// store, retrieve, and deduplicate operations. Merge semantics (which
/// operation wins) live in `src/crdt/*` and are applied by [SyncedDoc] and
/// friends after reading operations back out of the store.
///
/// Two implementations ship in this package: [InMemoryLocalStore] (pure
/// Dart, no I/O — good for tests and ephemeral usage) and
/// [DriftLocalStore] (SQLite-backed, durable across app restarts).
abstract class LocalStore {
  /// Opens/creates the underlying storage. Must be called before any other
  /// method.
  Future<void> init();

  /// Releases underlying resources (database connections, etc).
  Future<void> close();

  /// Records operations generated locally (e.g. by [SyncedDoc.update]).
  /// These are immediately visible to [opsForDoc] and are considered
  /// pending for every sync adapter until [markPushed] is called for that
  /// adapter.
  Future<void> appendLocalOps(List<Operation> ops);

  /// Records operations received from a remote sync adapter, skipping any
  /// whose [Operation.id] has already been seen (from either a local write
  /// or an earlier pull) — the idempotency guarantee the CRDT merge layer
  /// relies on. Operations ingested this way are marked already-pushed to
  /// [adapterId], so the engine never echoes them straight back.
  ///
  /// Returns only the operations that were newly stored (i.e. actually
  /// new to this device), which is what the caller should feed through
  /// the CRDT merge functions.
  Future<List<Operation>> ingestRemoteOps(
    String adapterId,
    List<Operation> ops,
  );

  /// Operations for [adapterId] that have not yet been pushed.
  Future<List<Operation>> pendingOps(String adapterId, {int? limit});

  /// Marks the given operation ids as pushed to [adapterId], so they are
  /// excluded from future [pendingOps] calls for that adapter.
  Future<void> markPushed(String adapterId, Iterable<String> opIds);

  /// All operations recorded for [docId], in insertion order. Used to
  /// rebuild a document's CRDT state from scratch (e.g. on first load, or
  /// when no snapshot is available).
  Future<List<Operation>> opsForDoc(String docId);

  /// All operations ever recorded, oldest first. Primarily for the debug
  /// [SyncKitInspector] widget.
  Future<List<Operation>> allOps();

  /// Emits a batch every time [appendLocalOps] or [ingestRemoteOps] adds
  /// new operations.
  Stream<OpBatch> get changes;

  /// The last sync checkpoint recorded for [adapterId] (opaque cursor
  /// defined by the adapter — e.g. a server sequence number or ISO
  /// timestamp), or `null` if this device has never successfully pulled
  /// from it.
  Future<String?> getCheckpoint(String adapterId);

  /// Persists the sync checkpoint for [adapterId].
  Future<void> setCheckpoint(String adapterId, String checkpoint);
}
